language: python
python:
  - "3.6" 
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
# command to run tests
script:
  - coverage -m unittest tests/flask_test.py
after_success:
  - codecov
